---
title: "Publications"
date: "05/6/2019"
output:
  prettydoc::html_pretty:
    highlight: github
    theme: cayman
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Benoit, C., Smith, M., Jansson, M., Healey, P., & Magnuson, D. (2019). Delinking Prostitution and Sex Trafficking: Response to Commentaries. *Archives of Sexual Behavior*. Available: https://link.springer.com/article/10.1007/s10508-019-1461-2

Benoit, C., Maurice, R., Abel, G., Smith, M., Jansson, M., Healey, P., & Magnuson, D. (2019). "I dodged the stigma bullet:" Canadian Sex Workers' situated response to occupational stigma. *Culture, Health, & Sexuality: An international journal for research, intervention, and care.* https://doi.org/10.1080/13691058.2019.1576226

Magnuson, D., Jansson, M., Benoit, C. (2019). Foster care as a support system for early leavers. In Varda Mann-Feder, (ed). *Leaving Care and the Transition to Adulthood: International Contributions to Theory, Research, and Practice.* Oxford University Press.

Snell, H. Stuart, C., & Magnuson, D. (2019). Post-secondary education as a crucible for learning practice. In K. Girabaghi & G. Charles (eds.), *Child & Youth Care Across Sectors vol 1.* Canadian Scholars Press. 

Carty, E., & Harper, N. (2019). Outdoor adventure and CYC practice. In K. Girabaghi & G. Charles (eds.), *Child & Youth Care Across Sectors vol 1* Canadian Scholars Press. 

Benoit, C., Smith, M., Jansson, M., Healey, P., & Magnuson, D. (2018). The 'prostitution problem:' claims, evidence, and policy outcomes. *Archives of Sexual Behavior*: https://doi.org/10.1007/s10508-018-1276-6

Magnuson, D., Jansson, M., & Benoit, C. (2018). "I feel like I've really grown up: A brief report on street-involved youth. *Research to practice network, 2*(1). Available: https://fcssbc.ca/sf-docs/r2p/2018_magnuson.pdf

Magnuson, D. (in press). "I feel like I've really grown up:" *The experience of emerging adulthood among street-involved youth.* Oxford University Press. 

Magnuson, D. (2018). What's wrong with professional consultations? *CYC-Online*, *236*. 

Magnuson, D., & Healey, P. (2018). The statistical reason why youth work ought to be voluntary.  *CYC-Online*, *236*. 

Magnuson, D., & Healey, P. (2018). The multi-armed bandit algorithm. *CYC-Online*, *234,* 30-33. 

Magnuson, D., & Vachon, W. (2018). Being competent about competence. *CYC-Online*, *231,* 22-24.
  
Magnuson, D. (2018). Why relationships are left out of evaluations. *CYC-Online*, *227,* 21-23. 
  
Kennedy, M.C., Jansson, M., Benoit, C., Magnuson, D., Scramstad, J., Halgrimsdottir, H. (2017). Social support among street-involved youth. *Journal of Youth Studies, 20*(10), pp. 1328-1345. To link to this article: http://dx.doi.org/10.1080/13676261.2017.1333582  

 Magnuson, D. (2017). How to ask for help. *CYC-Online, 225,* 26-29.   

Magnuson, D., & McGrath, J. (2017). How to choose a CYC program: an investigation. *CYC-Online, 224*, 11-13. 

Magnuson, D. (2017). The narrative fallacy.   CYC-Online,  221, 11-13. 

Magnuson, D. (2017). The pragmatic youth worker: idiographic evidence-based practice. *CYC-Online,  219,* 16-18. 

Magnuson, D. (2017). Why you should worry about clinical judgment and interviews.  *CYC-Online,  217*, 31-33. 

Magnuson, D. (2017). Data collection and use as practice. *CYC-Online,  215,* 30-32. 

Magnuson, D. (2016). The naivete of evidence-based practice.   CYC-Online,  213, 20-21. 

Magnuson, D. (2016). Propaganda with and without evidence.   CYC-Online,  211, pp. 19-21. 

Magnuson, D. (2016). Signs and symptoms in child and youth care evaluation.   *CYC-Online,  209,* 24-26. 

Magnuson, D. (2016). Falsify that theory. *CYC-Online,  207*, 24-26. 

Magnuson, D. (2016). The use of group data in CYC practice. *CYC-Online,  205*, 21-23. 

Magnuson, D. (2015). How small sample sizes deceive us. *CYC-Online,  203,* 14-16. 

Magnuson, D., Jansson, M., Benoit, C., & Kennedy, M. C. (2015). Instability and caregiving in the lives of street-involved children from foster care. *Child and Family Social Work.*  http://doi.wiley.com/10.1111/cfs.12262

Magnuson, D. (2014). The productive use of conflict in child protection. *Social Sciences,* 672-686. 

Magnuson, D. (2014). Stop breaking people into bits: A plea for a peopled youthwork. In K. Gharabaghi, M. Krueger, & H. Skott-Myre (eds.), *With Children.* Wilfred Laurier Press.

Magnuson, D. & Baldin, C. (2014). A defence of professionalism: a response to Fusco and Baizerman. *Child & Youth Services, 35*(1), 4-15.

Emerson, D., & Magnuson, D. (2013). Child protection intervention in domestic violence. An illustrative case narrative. *Child & Youth Services, 34*(3), 236-249.

Magnuson, D. (2011). Negotiation as a style in child protection work. *Child & Family Social Work.* doi:10.1111/j.1365-2206.2011.00780.x10.1111/j.1365-2206.2011.00780.x

Magnuson, D. (2009). The need for the study of everyday life about youth work practice in divided societies. *Youth and Policy, 102*, 21-24.
	
Magnuson, D. (2009). The contribution of spirituality to “becoming a self” in child and youth services. In M. de Souza, L. Francis, J. O’Higgens-Norman, & D. Scott. *International Handbook of Education for Spirituality, Care, and Well-being* (pp. 433-452). New York: Springer.
	
Artz, S., Nicholson, D., & Magnuson, D. (2008). Examining sex differences in the use of direct and indirect aggression. *Gender Issues 25*(4), 267-288.
	
Magnuson, D. (2007). The perils, promise, and practice of youthwork in conflict societies. In D. Magnuson & M. Baizerman (Eds.), *Work with youth individed and contested societies.* Rotterdam: Sense Publishing. [edited volume also listed in books]
	
Magnuson, D. & Baizerman, M. (Eds.) (2007). *Work with youth in divided and contested societies.*  Rotterdam: Sense Publishing.
	
Romi, S., Magnuson, D., & Ferguson, R. (2007). Child and youth care in higher education. In H. Grietens, E. J. Knorth, P. Durning, & J. E. Dumas (Eds.), *Promoting competence in children and families: scientific perspectives on resilience and vulnerability* (pp. 375-400).
	
Dieser, R. B., Magnuson, D., & Scholl, K. (2005). Critically rethinking the benefits-based approach from a cross-cultural perspective. *Philosophy of Therapeutic Recreation: Ideas and Issues,* Volume III (pp. 59-72). National Therapeutic Recreation and Park Association.
	
Scott, D., & Magnuson, D. (2005) Integrating spiritual development into child and youth care programs and institutions. In Benson, P. L., Roehlkepartain, E. C., King, P. E., & Wagener, L. (Eds.), *The Handbook of spiritual development in childhood and adolescence* (pp. 445-457).  Thousand Oaks, CA: Sage Publications.  

Baldwin, C., Hutchinson, S. L., Magnuson, D. (2004). Program theory: A framework for theory-driven programming and evaluation. *Therapeutic Recreation Journal*, 34, 16-21.
	
Baldwin, C., Persing, J., & Magnuson, D. (2004). The role of theory in research and evaluation about adventure education. *Journal of Experiential Education,* 26(3), 167-183.
	
Coleman, M., Magnuson, D., Randall, S., & Stringer, A.  (2003). Situated friendship: Goal and identity in an after-school girls program.  *Relational Child & Youth Care Practice 16*(1), 21-34.
	
Magnuson, D., Baldwin, C., Baizerman, M., & Stringer, A. (2003). Adolescence or youth?  Background to developmental practice. *Journal of Child & Youth Care Work, 18*. 60-70.
	
Magnuson, D., Baizerman, M., & Lundgren, K. (2003). Challenges to discernment in religious education. *Religion and Education, 30*(2), 45-61.
	
Magnuson, D., & Burger, L. (2002). Developmental supervision in residential care. *Journal of Child and Youth Care, 15*(2), 9-22.
	
Magnuson, D., Hudson, S., & Baldwin, C. (2002). Community youth development reconsidered: A look at some origins of our practices. *Community Youth Development Anthology*, 55-62.
	
Magnuson, D., Baizerman, M., & Stringer, A. (2001). A moral praxis of child and youth care work. *Journal of Child and Youth Care, 15-16*, 302-312.
	
Richter, D., Magnuson, D., & Baizerman, M. (1998). Reconceiving youth ministry. *Religious Education, 93*(3), 340-357.
	
Magnuson, D. (1997). A response to “Residential Treatment and its Alternatives:” Toward a broader paradigm. *Child and Youth Care Forum, 26*(1), 57-61.
	
Beker, J., & Magnuson, D. (Eds.). (1996). *Residential education as an option for at-risk youth.* New York:  Haworth Press. 
	
Magnuson, D. (1996).  Essential moral sources of ethical standards in child and youth care work. *Child and Youth Care Forum, 24*(6), 405-411.
	
Magnuson, D. (1996). Empirical research and prescriptive models. *Child and Youth Care Forum*, 25(5), 293-296.
	
Baizerman, M., & Magnuson, D. (1996).  Do we still need youth as a social stage?  Young: *Nordic Journal of Youth Research, 4*(3), 48-60.
	
Magnuson, D., Bachman, R., & Theunissen, V. (1996).  Perspective taking and socialization of staff. *Child and Youth Care Forum, 25*(6), 379-392.
	
Beker, J., & Magnuson, D. (1996).  Residential education: Some questions, some suggestions, and a look ahead.  *Residential Treatment for Children and Youth, 13*(3), 117-124.
	
Beker, J., & Magnuson, D. (1996). Residential education as an option for at-risk youth: Learning from the Israeli experience. *Residential Treatment for Children & Youth, 13*(3), 3-48.
	
Magnuson, D., Barnes, F. H., & Beker, J. (1996). Human development imperatives in the organization of group care programs: A practical approach. *Residential Treatment for Children and Youth, 13*(3), 85-97.
	
Johnson, D. W., Johnson, R. T., Dudley, B., Ward, M., & Magnuson, D. (1995).  The impact of peer mediation training on the management of school and home conflicts.  *American Educational Research Journal, 32*(4), 829-844.
	
Johnson, D. W., Johnson, R. T., Dudley, B., & Magnuson, D. (1995). Training elementary students to manage conflict.  *Journal of Social Psychology, 135*(6), 673-686.
	
Magnuson, D. (1994). Responding with restraint. *Child and Youth Care Forum, 23*(1), 33-36.